# Edit this configuration file to define what should be installed on
# your system.  Help is available in the configuration.nix(5) man page
# and in the NixOS manual (accessible by running ‘nixos-help’).

{ config, pkgs, modulesPath, ... }:

{
  imports =
    [
      # Include the default lxd configuration.
      "${modulesPath}/virtualisation/lxc-container.nix"
      # Include the container-specific autogenerated configuration.
      ./lxd.nix
      # Include the OrbStack-specific configuration.
      ./orbstack.nix
    ];

  # users.users.super-ben = {
  #   uid = 501;
  #   extraGroups = [ "wheel" ];

  #   # simulate isNormalUser, but with an arbitrary UID
  #   isSystemUser = true;
  #   group = "users";
  #   createHome = true;
  #   home = "/home/ben";
  #   homeMode = "700";
  #   useDefaultShell = true;
  # };

  nixpkgs.config = {
    allowUnfree = true;
  };

  security.sudo.wheelNeedsPassword = false;

  virtualisation.docker.enable = true;

  # This being `true` leads to a few nasty bugs, change at your own risk!
  users.mutableUsers = false;

  time.timeZone = "Europe/Lisbon";

  networking = {
    # nameservers = [ "1.1.1.1" "9.9.9.9" ];
    # interfaces.eth0.mtu = 1400;
    dhcpcd.enable = false;
    useDHCP = false;
    useHostResolvConf = false;
  };

  systemd.network = {
    enable = true;
    networks."50-eth0" = {
      matchConfig.Name = "eth0";
      networkConfig = {
        DHCP = "ipv4";
        IPv6AcceptRA = true;
      };
      linkConfig = {
        RequiredForOnline = "routable";
        MTUBytes = "1400";
      };
    };
  };

  system.stateVersion = "24.05"; # Did you read the comment?
}
